### ISSUE TITLE
Tutorial is not properly accurate

### ISSUE THREAD

**Issue by Pertence** [masc-ucsc/esesc#10]
While trying to run the step 6,  the terminal says some file are missing.
But, I found a solution. Instead of executing step 5 like the tutorial, execute this 
cp ~/projs/esesc/conf/* ~/build/release/run
cp ~/projs/esesc/bins/mips64/* ~/build/release/run
That will copy the missing files.

**Comment by renau** [comment]
Yes, the code has evolve and the tutorial is not longer accurate.
